spring:
  application:
    name: api-gateway

server:
  port: 8080

zuul:
  ribbon:
    eager-load:
      enabled: true
  retryable: true
  prefix: /api
  routes:
    HELLO-SERVICE:
      path: /greet/**
      serviceId: helloservice-svc
      strip-prefix: true
    HELP-SERVICE:
      path: /request/**
      serviceId: helpservice-svc
      strip-prefix: true
      
logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
  level:
    org:
      apache:
        http:
          wire: debug
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
