kind: ConfigMap
apiVersion: v1
metadata:
  name: api-gateway
data:
  application.yaml: |-
    zuul:
      ribbon:
        eager-load:
          enabled: true
      retryable: true
      prefix: /api
      routes:
        HELLO-SERVICE:
          path: /greet/**
          serviceId: helloservice-svc
          strip-prefix: false
        HELP-SERVICE:
          path: /request/**
          serviceId: helpservice-svc
          strip-prefix: false
      
