apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  labels:
    app: spring-boot-k8s-api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-k8s-api-gateway
  template:
    metadata:
      labels:
        app: spring-boot-k8s-api-gateway
    spec:
      containers:
      - name: gateway-service
        image: gateway-service
        imagePullPolicy: Never
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 2
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-svc
  labels:
    app: spring-boot-k8s-api-gateway
spec:
  type: NodePort
  ports:
  - port: 31236
    nodePort: 30125
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: spring-boot-k8s-api-gateway
